name: ticket_reselling
description: "Ticker Reselling is cross platform app made in flutter with ❤️ in vrinsoft."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #storage
  shared_preferences: ^2.2.3

  #utils
  intl: ^0.19.0
#  fk_user_agent: ^2.1.0
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1

  #network
  dio: ^5.7.0

  #state management
  get: ^4.6.6
  location: ^7.0.1
#  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/